# flake8: noqa

import typing

class AlertMsg:
    SLOT_TYPES: typing.Tuple
    def __init__(
        self,
        threshold: float = float(),
        actual: float = float(),
        warning: bool = bool(),
        critical: bool = bool(),
        target: typing.List[str] = list(),
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> typing.Dict[str, str]: ...
    @property
    def threshold(self) -> float: ...
    @threshold.setter
    def threshold(self) -> None: ...
    @property
    def actual(self) -> float: ...
    @actual.setter
    def actual(self) -> None: ...
    @property
    def warning(self) -> bool: ...
    @warning.setter
    def warning(self) -> None: ...
    @property
    def critical(self) -> bool: ...
    @critical.setter
    def critical(self) -> None: ...
    # @property
    # def target(self) -> typing.List[str]: ...
    target: typing.List[str]

class ChopperMsg:
    SLOT_TYPES: typing.Tuple
    def __init__(self, insert: bool = bool(), time: float = float()) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> typing.Dict[str, str]: ...
    @property
    def insert(self) -> bool: ...
    @insert.setter
    def insert(self) -> None: ...
    @property
    def time(self) -> float: ...
    @time.setter
    def time(self) -> None: ...

class CoordCmdMsg:
    SLOT_TYPES: typing.Tuple
    def __init__(
        self,
        lon: typing.List[float] = list(),
        lat: typing.List[float] = list(),
        unit: str = str(),
        frame: str = str(),
        time: typing.List[float] = list(),
        name: str = str(),
        speed: float = float(),
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> typing.Dict[str, str]: ...
    @property
    def lon(self) -> typing.List[float]: ...
    @lon.setter
    def lon(self) -> None: ...
    @property
    def lat(self) -> typing.List[float]: ...
    @lat.setter
    def lat(self) -> None: ...
    @property
    def unit(self) -> str: ...
    @unit.setter
    def unit(self) -> None: ...
    @property
    def frame(self) -> str: ...
    @frame.setter
    def frame(self) -> None: ...
    @property
    def time(self) -> typing.List[float]: ...
    @time.setter
    def time(self) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self) -> None: ...
    @property
    def speed(self) -> float: ...
    @speed.setter
    def speed(self) -> None: ...

class CoordMsg:
    SLOT_TYPES: typing.Tuple
    def __init__(
        self,
        lon: float = float(),
        lat: float = float(),
        unit: str = str(),
        frame: str = str(),
        time: float = float(),
        name: str = str(),
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> typing.Dict[str, str]: ...
    @property
    def lon(self) -> float: ...
    @lon.setter
    def lon(self) -> None: ...
    @property
    def lat(self) -> float: ...
    @lat.setter
    def lat(self) -> None: ...
    @property
    def unit(self) -> str: ...
    @unit.setter
    def unit(self) -> None: ...
    @property
    def frame(self) -> str: ...
    @frame.setter
    def frame(self) -> None: ...
    @property
    def time(self) -> float: ...
    @time.setter
    def time(self) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self) -> None: ...

class PIDMsg:
    SLOT_TYPES: typing.Tuple
    def __init__(
        self,
        k_p: float = float(),
        k_i: float = float(),
        k_d: float = float(),
        axis: str = str(),
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> typing.Dict[str, str]: ...
    @property
    def k_p(self) -> float: ...
    @k_p.setter
    def k_p(self) -> None: ...
    @property
    def k_i(self) -> float: ...
    @k_i.setter
    def k_i(self) -> None: ...
    @property
    def k_d(self) -> float: ...
    @k_d.setter
    def k_d(self) -> None: ...
    @property
    def axis(self) -> str: ...
    @axis.setter
    def axis(self) -> None: ...

class TimedAzElFloat64:
    SLOT_TYPES: typing.Tuple
    def __init__(
        self, az: float = float(), el: float = float(), time: float = float()
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> typing.Dict[str, str]: ...
    @property
    def az(self) -> float: ...
    @az.setter
    def az(self) -> None: ...
    @property
    def el(self) -> float: ...
    @el.setter
    def el(self) -> None: ...
    @property
    def time(self) -> float: ...
    @time.setter
    def time(self) -> None: ...

class TimedAzElInt64:
    SLOT_TYPES: typing.Tuple
    def __init__(
        self,
        az: int = int(),
        el: int = int(),
        time: float = float(),
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> typing.Dict[str, str]: ...
    @property
    def az(self) -> int: ...
    @az.setter
    def az(self) -> None: ...
    @property
    def el(self) -> int: ...
    @el.setter
    def el(self) -> None: ...
    @property
    def time(self) -> float: ...
    @time.setter
    def time(self) -> None: ...

class TimedFloat64:
    SLOT_TYPES: typing.Tuple
    def __init__(
        self,
        data: float = float(),
        time: float = float(),
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> typing.Dict[str, str]: ...
    @property
    def data(self) -> float: ...
    @data.setter
    def data(self) -> None: ...
    @property
    def time(self) -> float: ...
    @time.setter
    def time(self) -> None: ...
