# flake8: noqa

import typing

class AuthoritySrv:
    class Request:
        SLOT_TYPES: typing.Tuple
        def __init__(self, requester: str = str(), remove: bool = bool()) -> None: ...
        @classmethod
        def get_fields_and_field_types(cls) -> typing.Dict[str, str]: ...
        @property
        def requester(self) -> str: ...
        @requester.setter
        def requester(self, value: str) -> None: ...
        @property
        def remove(self) -> bool: ...
        @remove.setter
        def remove(self, value: bool) -> None: ...

    class Response:
        SLOT_TYPES: typing.Tuple
        def __init__(self, privilege: bool = bool()) -> None: ...
        @classmethod
        def get_fields_and_field_types(cls) -> typing.Dict[str, str]: ...
        @property
        def privilege(self) -> bool: ...
        @privilege.setter
        def privilege(self, value: bool) -> None: ...

class File:
    class Request:
        SLOT_TYPES: typing.Tuple
        def __init__(self, data: str = str(), path: str = str()) -> None: ...
        @classmethod
        def get_fields_and_field_types(cls) -> typing.Dict[str, str]: ...
        @property
        def data(self) -> str: ...
        @data.setter
        def data(self, value: str) -> None: ...
        @property
        def path(self) -> str: ...
        @path.setter
        def path(self, value: str) -> None: ...

    class Response:
        SLOT_TYPES: typing.Tuple
        def __init__(self, success: bool = bool()) -> None: ...
        @classmethod
        def get_fields_and_field_types(cls) -> typing.Dict[str, str]: ...
        @property
        def success(self) -> bool: ...
        @success.setter
        def success(self, value: bool) -> None: ...

class RecordSrv:
    class Request:
        SLOT_TYPES: typing.Tuple
        def __init__(self, name: str = str(), stop: bool = bool()) -> None: ...
        @classmethod
        def get_fields_and_field_types(cls) -> typing.Dict[str, str]: ...
        @property
        def name(self) -> str: ...
        @name.setter
        def name(self, value: str) -> None: ...
        @property
        def stop(self) -> bool: ...
        @stop.setter
        def stop(self, value: bool) -> None: ...

    class Response:
        SLOT_TYPES: typing.Tuple
        def __init__(self, recording: bool = bool()) -> None: ...
        @classmethod
        def get_fields_and_field_types(cls) -> typing.Dict[str, str]: ...
        @property
        def recording(self) -> bool: ...
        @recording.setter
        def recording(self, value: bool) -> None: ...
