name: Documentation

on:
  release:
    types:
      - created
  workflow_dispatch:


jobs:
  compile:
    name: BuildAndPublishDocumentation
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-base
    env:
      PACKAGE_NAME: necst
      PACKAGE_PATH: ros2_ws/src/${{ github.event.repository.name }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set-up NECST
        uses: ./.github/actions/setup-necst
      - name: Install dependencies
        run: |
          pip3 install sphinx
      - name: Build docs
        working-directory: ${{ env.PACKAGE_PATH }}
        run: |
          poetry run sphinx-apidoc -efTM -t docs/_templates/apidoc -o docs/_source ${{ env.PACKAGE_NAME }}
          poetry run sphinx-build -a docs docs/_build
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build
