name: Documentation

on:
  release:
    types:
      - published

jobs:
  compile:
    name: BuildAndPublishDocumentation
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-base
    env:
      PACKAGE_NAME: necst
      PACKAGE_PATH: ros2_ws/src/${{ github.event.repository.name }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set-up NECST
        uses: ./.github/actions/setup-necst
      - name: Install correct versions of pip and setuptools
        run: |
            pip install --upgrade pip==24.1.2
            pip install setuptools==70.3.0
      - name: Install dependencies
        run: |
          pip3 install \
            "myst-parser==0.18.0" \
            "pydata-sphinx-theme==0.7.2" \
            "sphinx==5.0.0" \
            ${{ env.PACKAGE_PATH }}
      - name: Build docs
        working-directory: ${{ env.PACKAGE_PATH }}
        run: |
          . /opt/ros/$ROS_DISTRO/setup.bash
          . ../../install/setup.bash
          sphinx-apidoc -efTM -t docs/_templates/apidoc -o docs/_source ${{ env.PACKAGE_NAME }}
          sphinx-build -a docs docs/_build
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.PACKAGE_PATH }}/docs/_build
