name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    name: ROSPackagePythonTesting
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-base
    env:
      PACKAGE_NAME: necst
      ROS_DISTRO: humble
      PACKAGE_PATH: ros2_ws/src/${{ github.event.repository.name }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          path: ${{ env.PACKAGE_PATH }}

      - name: Build ROS package
        run: |
          echo ${{ env.ROS_DISTRO }}
          . /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          cd ros2_ws
          colcon build --symlink-install

      - name: python_testing
        run: |
          . /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          (apt-get update) && (apt-get upgrade)
          apt-get python3-pip
          pip3 install neclib
          ls
          cd ros2_ws/src/necst
          python3 -m pytest tests
