name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  runs-on: ubuntu-latest
  compile:
    name: ROSPackagePythonTesting
    uses: ./.github/workflows/setup-necst.yml
    steps:
      - name: python testing
        run: |
          . /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          cd ros2_ws
          . install/setup.bash
          cd src/necst
          python3 -m pytest -v tests
