name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    name: ROSPackagePythonTesting
    runs-on: ubuntu-latest
    container:
      image: ...
    steps:
      - name: Set-up NECST environment
        uses: ./.github/workflows/setup-necst.yml
      - name: python testing
        run: |
          . /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          cd ros2_ws
          . install/setup.bash
          cd src/necst
          python3 -m pytest -v tests
