name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    name: ROSPackagePythonTesting
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-base
    env:
      PACKAGE_NAME: necst
      PACKAGE_PATH: ros2_ws/src/${{ github.event.repository.name }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set-up NECST
        uses: ./.github/actions/setup-necst
      - name: Install test dependency
        run: |
          pip install \
            "myst-parser==0.18.0" \
            "pydata-sphinx-theme==0.7.2" \
            "pytest-cov==3.0.0" \
            "sphinx==4.5.0"
      - name: python testing
        run: |
          . /opt/ros/$ROS_DISTRO/setup.bash
          cd ros2_ws
          . install/setup.bash
          cd src/necst
          python3 -m pytest --cov --cov-report xml -v tests
      - name: Upload code coverage report
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          working-directory: ${{ env.PACKAGE_PATH }}
          token: ${{ secrets.CODECOV_TOKEN }}
